### ISSUE TITLE
Migrating to UAVCAN 1.0

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/embedded#10]
We will migrate to UAVCAN v1 once libcanard has official support for it.

I haven't looked in-depth at the new specification yet, but it looks like it won't be plug and play. (for one, there are no actuator commands, at least when I looked).

**Comment by pavel-kirienko** [comment]
> I haven't looked in-depth at the new specification yet, but it looks like it won't be plug and play. (for one, there are no actuator commands, at least when I looked).

It is plug-and-play. The major difference is that there won't be any application-specific standard data types anymore, because they were considered as being too scope-limited to be included in the general specification. Instead, implementers are advised to either rely on third-party vendor-specific data types (if the license permits; we're going to encourage the use of the MIT license), define their own data types, or use the generic types defined in the namespaces `uavcan.si` (where "si" stands for SI - the international system of units) and `uavcan.primitive` (which is just a collection of primitive scalars and arrays, e.g. you could pack your actuator commands into `uavcan.primitive.array.Natural16`). For reference, here is the UAVCAN v1.0 branch in the DSDL repo: https://github.com/UAVCAN/dsdl/tree/uavcan-v1.0/uavcan
